name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/react

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Check Version & Lockfile Updated
        run: |
          CURRENT_VERSION=$(jq -r .version ./package.json)
          git fetch origin main
          BASE_VERSION=$(git show origin/main:packages/react/package.json | jq -r .version)

          echo "Current version: $CURRENT_VERSION"
          echo "Base version: $BASE_VERSION"

          if [ "$CURRENT_VERSION" = "$BASE_VERSION" ]; then
            echo "::error::ğŸš¨ package.jsonì˜ ë²„ì „ì´ ë³€ê²½ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."
            exit 1
          fi

          # ğŸ” package-lock.jsonë„ ë³€ê²½ë˜ì—ˆëŠ”ì§€ í™•ì¸
          git diff --quiet origin/main -- ./package-lock.json
          if [ $? -ne 0 ]; then
            echo "âœ… package-lock.jsonì´ ë³€ê²½ë˜ì—ˆìŠµë‹ˆë‹¤."
          else
            echo "::error::ğŸš¨ package-lock.jsonì´ ë³€ê²½ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."
            exit 1
          fi

      - name: Run Tests
        run: npm test

      - name: Run Build
        run: npm run build
